FROM node:16-alpine

WORKDIR /app

# Install the required packages
RUN apk add --update --no-cache bash python3 make g++ git

# Copy package files
COPY package.json package-lock.json* ./

# Install dependencies
RUN npm ci

# Copy the rest of the code
COPY . .

# Compile the contracts
RUN npm run compile

CMD ["npm", "run", "migrate"] 